### ISSUE TITLE
Invalid action

### ISSUE THREAD

**Issue by fahmishah** [srehanuddin/Cordova-Plugin-Bluetooth-Printer#16]
I am trying to print some string using this plugin but I got error

When trying to go to `BTPrint.printText` function, it gaves me `invalid action`

then I got `Read failed, socket might closed or timeout, read ret: -1` after click the same button.

My code as follows;

         $scope.connectPrinter = function(name) {

           $scope.test = "\n Muahahahahah \n Muahahahahah \n Muahahahahah \n \n \n \n";

           BTPrinter.connect(function(data) {
             alert("Success");
             alert(data);
             
            BTPrinter.printText(function(data) {
              alert("Success");
              alert(data);

              BTPrinter.disconnect(function(data) {
                alert("Success");
                alert(data);
              }, function(err){
                alert("Error");
                alert(err);
              }, "name")

            }, function(err){
              alert("Error");
              alert(err)
            }, $scope.test)
             
            }, function(err){
              alert("Error");
              alert(err);
            }, name)
         };

Can anyone assist me?

**Comment by wonk4rol** [comment]
the solution in here https://github.com/srehanuddin/Cordova-Plugin-Bluetooth-Printer/issues/5#issuecomment-247338434

**Comment by fahmishah** [comment]
@wonk4rol thank you very much!

**Comment by srehanuddin** [comment]
Issue fix on master branch
