### ISSUE TITLE
Option for selecting device type 

### ISSUE THREAD

**Issue by Reshmank** [srehanuddin/Cordova-Plugin-Bluetooth-Printer#31]
if there is any option for selecting device type for our bluetooth printer plugin ? assume  there a so any paired device in our mobile,then how can i select perticular bluetooth device to mobile . there is any option for that ? am waiting for your reply

**Comment by srehanuddin** [comment]
Yes, by list method you can populate list of all paired bluetooth devices, by this user can select any printer and you can connect that printer by connect method, in which printer name passed as argument.
