### ISSUE TITLE
Is it possible print image in ionic 2 ?

### ISSUE THREAD

**Issue by Fiv38** [srehanuddin/Cordova-Plugin-Bluetooth-Printer#45]
i tried to print image with this plugin in ionic 1 and the result is nice as expected.
but when i tried to print image with this plugin in ionic 2, it print unknown character.

is it possible to print image in ionic 2 ?

thank you for this awesome plugin. keep up good work dude.

**Comment by srehanuddin** [comment]
it doesnt matter ionic 1 or ionic 2, its uses cordova to print

**Comment by Fiv38** [comment]
thank @srehanuddin for your reply, 
actually i was used the plugin correctly in ionic 2. and all the function is working. 

but when i try to print image, the image is unknown character. so i just wondering is it possible or not. i will research more to make sure your plugin working in ionic 2.

Thank you dude, keep up good work !

**Comment by sahilmo** [comment]
@Fiv38 have you got the idea how to use this plugin in ionic 2 to print image. Please help i am not getting any idea how to do that?

**Comment by sahilmo** [comment]
@Fiv38 @srehanuddin i tried with the plugin that is working but while printing image unkown character printing. What is the solution for it ? Can you please help on it?
