### ISSUE TITLE
print text

### ISSUE THREAD

**Issue by gmosornoza** [srehanuddin/Cordova-Plugin-Bluetooth-Printer#5]
Hi, when i'm using the printText code snippet, i get the error "Invalid action".

Regards.

**Comment by pressplaylf** [comment]
correction: The one for printText is missing.

**Comment by konlawatch** [comment]
i want to simple code. please.

**Comment by wonk4rol** [comment]
@pressplaylf it works, thanks

**Comment by adamix24** [comment]
@pressplaylf Thanks, work for my.

**Comment by nakalissi** [comment]
Hi, this fix has been updated to master?

**Comment by Luchillo** [comment]
@nakalissi No it has not, idk why it hasn't been updated but it should.

**Comment by surendiranganesan** [comment]
kindly updated the fix to the master. its creating problem while taking build from https://build.phonegap.com

**Comment by Luchillo** [comment]
@surendiranganesan You know what i did? i pulled a fork from this repo, in which someone had added this fix, in cordova you can install plugins directly from github, go look the few forks (i don't remember how many are there, think like 5) to see which one works for you, take in account the branch, if the fix is in a branch you'll have to pull that branch when installing the plugin.

**Comment by surendiranganesan** [comment]
Thank you very much @Luchillo. there are few forked repos which contained the fix. so i used one of them

**Comment by srehanuddin** [comment]
Issue fix on master branch

**Comment by luchillo17** [comment]
@srehanuddin Thanks man, btw is it already in the cordova plugin database or we still need to install from github?

If not, when will it be?

**Comment by luchillo17** [comment]
Another thing, i'm printing in spanish and this character `¡`, is not used in english, so how would i make it happen? it shows a weird subindexed `T`and a weird `í` instead.

I was taking a look at http://stackoverflow.com/questions/5396560/how-do-i-convert-special-utf-8-chars-to-their-iso-8859-1-equivalent-using-javasc thinking it's an encoding issue.
