### ISSUE TITLE
Blue tooth Printer Connection

### ISSUE THREAD

**Issue by Chandrakala14** [srehanuddin/Cordova-Plugin-Bluetooth-Printer#7]
Hi, I am not able to connect my bluetooth printer ., getting connected  first time and after few seconds immediately got connection aborted error.Please help me

**Comment by wonk4rol** [comment]
please share your error guys

**Comment by Chandrakala14** [comment]
hi, My error was solved. Thank you for the nice plugin.


Now I m having small problem.I am not able to print the words. After pressing two or more times .It is coming continuously without any spaces. Please Help me.

**Comment by wonk4rol** [comment]
try to add begining and ending of string with "\n"

**Comment by ainulya16** [comment]
i can't print with max of number characters
maybe 100

**Comment by Chandrakala14** [comment]
thank you .It was fixed @wonk4rol

**Comment by GbalsaC** [comment]
This should be closed
